@startuml

title __LOG121LAB2's Class Diagram__\n

  namespace bungo {
    class bungo.Bungo {
    }
  }
  

  namespace bungo {
    class bungo.StrategieBungo {
            + calculerLeVainqueur()
            + calculerScoreTour()
    }
  }
  

  namespace framework {
    class framework.DeCollection {
    - tabDe : De[]
    + add()
    + iterator()
    }
  }
  

  namespace framework {
    class framework.PlayerCollection {
    - tabPlayer : Player[]
    + add()
    + iterator()
    }
  }
  

  namespace framework {
    class framework.De {
    - nbFaces : int
    + compareTo()
    }
  }
  

  namespace framework {
    class framework.Factory {
            + creerDes()
            + creerJeu()
            + creerJoueurs()
            + creerPartie()
    }
  }
  

  namespace framework {
    interface framework.IStrategie {
            {abstract} + calculerLeVainqueur()
            {abstract} + calculerScoreTour()
    }
  }
  

  namespace framework {
    abstract class framework.Jeu {
            - nbTours : int
            + calculerLeVainqueur()
            + calculerScoreTour()
    }
  }
  

  namespace framework {
    class framework.Player {
    + compareTo()
    }
  }
  

  namespace framework {
    class framework.TabIterator {
    - tab : Object[]
    + hasNext()
     + next()
    }
  }
  

  namespace tests {
    class tests.DeTest {
    }
  }
  

  bungo.Bungo -up-|> framework.Jeu
  bungo.StrategieBungo .up.|> framework.IStrategie
  framework.DeCollection .up.|> java.util.Collection
  framework.PlayerCollection .up.|> java.util.Collection
  framework.De .up.|> java.lang.Comparable
  framework.Jeu --> framework.DeCollection : des
  framework.Jeu --> framework.PlayerCollection : joueurs
  framework.Jeu --> framework.IStrategie : strategie
  framework.Player .up.|> java.lang.Comparable
  framework.TabIterator .up.|> java.util.Iterator
  tests.DeTest o-- framework.De : de1
  tests.DeTest o-- framework.De : de2
  framework.DeCollection .up.> framework.TabIterator
  framework.PlayerCollection .up.> framework.TabIterator
  framework.DeCollection <-- framework.TabIterator
  framework.PlayerCollection <-- framework.TabIterator
  framework.Factory .up.> framework.Jeu
  framework.Factory .up.> framework.Player
  framework.Factory .up.> framework.De
  framework.Factory .up.> java.util.Collection
  framework.De --o framework.DeCollection
  framework.Player --o framework.PlayerCollection


  hide tests
  hide java.util
right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
